---
# 密码加密
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
  namespace: system
type: Opaque
data:
  password: MzcxYzQzNTVkMjk1MTY0OTZiYzA2OTM1M2JjMTBhNzU= # 密码

---
# 存储卷定义
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-5gi
  namespace: moon
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  hostPath:
    path: /nfs/data/moon/mysql

---
# 存储卷声明
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: moon
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs

---
# 部署
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps.moon/name: mysql
  name: mysql
  namespace: moon
spec:
  selector:
    matchLabels:
      apps.moon/name: mysql
  template:
    metadata:
      labels:
        apps.moon/name: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              # 使用加密后的密码
              valueFrom:
                secretKeyRef:
                  name: moon-mysql-root-password
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: moon-server-mysql-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: moon-server-mysql-volume
          persistentVolumeClaim:
            claimName: moon-mysql-pvc
---
# 服务
apiVersion: v1
kind: Service
metadata:
  labels:
    apps.moon/name: mysql-svc
  name: mysql-svc
  namespace: moon
spec:
  selector:
    apps.moon/name: mysql
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 31234