apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: system
  labels:
    apps.moon/name: moon-server-svc
spec:
  selector:
    apps.moon/name: moon-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 31080
    - name: grpc
      port: 9000
      targetPort: 9000
      nodePort: 31090
    - name: ws
      port: 8888
      targetPort: 8888
    - name: nginx
      port: 80
      targetPort: 80
      nodePort: 31008
  type: NodePort
