apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: system
  labels:
    apps.moon/name: moon-server
spec:
  selector:
    matchLabels:
      apps.moon/name: moon-server
  replicas: 1
  template:
    metadata:
      labels:
        apps.moon/name: moon-server
    spec:
      containers:
        - command:
          - "bash"
          - "-c"
          - "nginx && ./prom_server --conf=/config/config.yaml"
          image: moon-server:latest
          imagePullPolicy: IfNotPresent
          name: moon-server
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - mountPath: /config
              name: moon-server-config
            - mountPath: /app/db
              name: moon-server-sqlite-volume
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: moon-server
      terminationGracePeriodSeconds: 10
      volumes:
        - name: moon-server-config
          configMap:
            name: moon-server-config
        - name: moon-server-sqlite-volume
          # 挂载./db/init_sqlite.db
          persistentVolumeClaim:
            claimName: moon-sqlite-pvc


