// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v3.19.4
// source: admin/team/department.proto

package team

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDepartmentCreateDepartment = "/api.admin.team.Department/CreateDepartment"
const OperationDepartmentDeleteDepartment = "/api.admin.team.Department/DeleteDepartment"
const OperationDepartmentGetDepartment = "/api.admin.team.Department/GetDepartment"
const OperationDepartmentListDepartment = "/api.admin.team.Department/ListDepartment"
const OperationDepartmentSetDepartmentAdmin = "/api.admin.team.Department/SetDepartmentAdmin"
const OperationDepartmentUpdateDepartment = "/api.admin.team.Department/UpdateDepartment"

type DepartmentHTTPServer interface {
	// CreateDepartment 创建部门
	CreateDepartment(context.Context, *CreateDepartmentRequest) (*CreateDepartmentReply, error)
	// DeleteDepartment 删除部门
	DeleteDepartment(context.Context, *DeleteDepartmentRequest) (*DeleteDepartmentReply, error)
	// GetDepartment 获取部门详情
	GetDepartment(context.Context, *GetDepartmentRequest) (*GetDepartmentReply, error)
	// ListDepartment 获取部门列表（树）
	ListDepartment(context.Context, *ListDepartmentRequest) (*ListDepartmentReply, error)
	// SetDepartmentAdmin 设置部门管理员
	SetDepartmentAdmin(context.Context, *SetDepartmentAdminRequest) (*SetDepartmentAdminReply, error)
	// UpdateDepartment 更新部门
	UpdateDepartment(context.Context, *UpdateDepartmentRequest) (*UpdateDepartmentReply, error)
}

func RegisterDepartmentHTTPServer(s *http.Server, srv DepartmentHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/department", _Department_CreateDepartment0_HTTP_Handler(srv))
	r.PUT("/v1/department/{id}", _Department_UpdateDepartment0_HTTP_Handler(srv))
	r.DELETE("/v1/department/{id}", _Department_DeleteDepartment0_HTTP_Handler(srv))
	r.GET("/v1/department/{id}", _Department_GetDepartment0_HTTP_Handler(srv))
	r.GET("/v1/department", _Department_ListDepartment0_HTTP_Handler(srv))
	r.POST("/v1/department/admin", _Department_SetDepartmentAdmin0_HTTP_Handler(srv))
}

func _Department_CreateDepartment0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDepartmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentCreateDepartment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDepartment(ctx, req.(*CreateDepartmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateDepartmentReply)
		return ctx.Result(200, reply)
	}
}

func _Department_UpdateDepartment0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDepartmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentUpdateDepartment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDepartment(ctx, req.(*UpdateDepartmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateDepartmentReply)
		return ctx.Result(200, reply)
	}
}

func _Department_DeleteDepartment0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDepartmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentDeleteDepartment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDepartment(ctx, req.(*DeleteDepartmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteDepartmentReply)
		return ctx.Result(200, reply)
	}
}

func _Department_GetDepartment0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDepartmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentGetDepartment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDepartment(ctx, req.(*GetDepartmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDepartmentReply)
		return ctx.Result(200, reply)
	}
}

func _Department_ListDepartment0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDepartmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentListDepartment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDepartment(ctx, req.(*ListDepartmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDepartmentReply)
		return ctx.Result(200, reply)
	}
}

func _Department_SetDepartmentAdmin0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetDepartmentAdminRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentSetDepartmentAdmin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetDepartmentAdmin(ctx, req.(*SetDepartmentAdminRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetDepartmentAdminReply)
		return ctx.Result(200, reply)
	}
}

type DepartmentHTTPClient interface {
	CreateDepartment(ctx context.Context, req *CreateDepartmentRequest, opts ...http.CallOption) (rsp *CreateDepartmentReply, err error)
	DeleteDepartment(ctx context.Context, req *DeleteDepartmentRequest, opts ...http.CallOption) (rsp *DeleteDepartmentReply, err error)
	GetDepartment(ctx context.Context, req *GetDepartmentRequest, opts ...http.CallOption) (rsp *GetDepartmentReply, err error)
	ListDepartment(ctx context.Context, req *ListDepartmentRequest, opts ...http.CallOption) (rsp *ListDepartmentReply, err error)
	SetDepartmentAdmin(ctx context.Context, req *SetDepartmentAdminRequest, opts ...http.CallOption) (rsp *SetDepartmentAdminReply, err error)
	UpdateDepartment(ctx context.Context, req *UpdateDepartmentRequest, opts ...http.CallOption) (rsp *UpdateDepartmentReply, err error)
}

type DepartmentHTTPClientImpl struct {
	cc *http.Client
}

func NewDepartmentHTTPClient(client *http.Client) DepartmentHTTPClient {
	return &DepartmentHTTPClientImpl{client}
}

func (c *DepartmentHTTPClientImpl) CreateDepartment(ctx context.Context, in *CreateDepartmentRequest, opts ...http.CallOption) (*CreateDepartmentReply, error) {
	var out CreateDepartmentReply
	pattern := "/v1/department"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDepartmentCreateDepartment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DepartmentHTTPClientImpl) DeleteDepartment(ctx context.Context, in *DeleteDepartmentRequest, opts ...http.CallOption) (*DeleteDepartmentReply, error) {
	var out DeleteDepartmentReply
	pattern := "/v1/department/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDepartmentDeleteDepartment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DepartmentHTTPClientImpl) GetDepartment(ctx context.Context, in *GetDepartmentRequest, opts ...http.CallOption) (*GetDepartmentReply, error) {
	var out GetDepartmentReply
	pattern := "/v1/department/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDepartmentGetDepartment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DepartmentHTTPClientImpl) ListDepartment(ctx context.Context, in *ListDepartmentRequest, opts ...http.CallOption) (*ListDepartmentReply, error) {
	var out ListDepartmentReply
	pattern := "/v1/department"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDepartmentListDepartment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DepartmentHTTPClientImpl) SetDepartmentAdmin(ctx context.Context, in *SetDepartmentAdminRequest, opts ...http.CallOption) (*SetDepartmentAdminReply, error) {
	var out SetDepartmentAdminReply
	pattern := "/v1/department/admin"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDepartmentSetDepartmentAdmin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DepartmentHTTPClientImpl) UpdateDepartment(ctx context.Context, in *UpdateDepartmentRequest, opts ...http.CallOption) (*UpdateDepartmentReply, error) {
	var out UpdateDepartmentReply
	pattern := "/v1/department/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDepartmentUpdateDepartment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
