# 使用官方Node.js镜像作为基础镜像
FROM node:latest as builder

# 设置工作目录
WORKDIR /usr/src/app

# 将前端应用程序代码复制到容器中
COPY ./web .

# 设置yarn源
RUN yarn config set registry https://registry.npmmirror.com/

# 安装依赖
RUN yarn install

# 编译前端应用程序
RUN yarn run build-docker

# 部署到nginx最小系统
FROM nginx:stable-perl

# /usr/share/nginx/html
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80