apiVersion: v1
kind: Service
metadata:
  name: agent-svc
  namespace: system
  labels:
    apps.moon/name: moon-agent-svc
spec:
  selector:
    apps.moon/name: moon-agent
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 31081
    - name: grpc
      port: 9000
      targetPort: 9000
      nodePort: 31091
  type: NodePort
