resources:
  - namespace.yaml
  - server.yaml
  - server-config.yaml
  - server-service.yaml
  - agent.yaml
  - agent-config.yaml
  - agent-service.yaml
#  - mysql-server.yaml

generatorOptions:
  disableNameSuffixHash: true

