apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: system
  labels:
    apps.prometheus.manager/name: prometheus-manager-server-svc
spec:
  selector:
    apps.prometheus.manager/name: prometheus-manager-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 31080
    - name: grpc
      port: 9000
      targetPort: 9000
      nodePort: 31090
  type: NodePort
