// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: agent/load.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	api "prometheus-manager/api"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StrategyGroupAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StrategyGroupAllRequest) Reset() {
	*x = StrategyGroupAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_load_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategyGroupAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyGroupAllRequest) ProtoMessage() {}

func (x *StrategyGroupAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_load_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyGroupAllRequest.ProtoReflect.Descriptor instead.
func (*StrategyGroupAllRequest) Descriptor() ([]byte, []int) {
	return file_agent_load_proto_rawDescGZIP(), []int{0}
}

type StrategyGroupAllReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupList []*api.GroupSimple `protobuf:"bytes,1,rep,name=groupList,proto3" json:"groupList,omitempty"`
}

func (x *StrategyGroupAllReply) Reset() {
	*x = StrategyGroupAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_load_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategyGroupAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyGroupAllReply) ProtoMessage() {}

func (x *StrategyGroupAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_load_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyGroupAllReply.ProtoReflect.Descriptor instead.
func (*StrategyGroupAllReply) Descriptor() ([]byte, []int) {
	return file_agent_load_proto_rawDescGZIP(), []int{1}
}

func (x *StrategyGroupAllReply) GetGroupList() []*api.GroupSimple {
	if x != nil {
		return x.GroupList
	}
	return nil
}

type StrategyGroupDiffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StrategyGroupDiffRequest) Reset() {
	*x = StrategyGroupDiffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_load_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategyGroupDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyGroupDiffRequest) ProtoMessage() {}

func (x *StrategyGroupDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_load_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyGroupDiffRequest.ProtoReflect.Descriptor instead.
func (*StrategyGroupDiffRequest) Descriptor() ([]byte, []int) {
	return file_agent_load_proto_rawDescGZIP(), []int{2}
}

type StrategyGroupDiffReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppendItems []*api.GroupSimple `protobuf:"bytes,1,rep,name=appendItems,proto3" json:"appendItems,omitempty"`
	DeleteItems []*api.GroupSimple `protobuf:"bytes,2,rep,name=deleteItems,proto3" json:"deleteItems,omitempty"`
	UpdateItems []*api.GroupSimple `protobuf:"bytes,3,rep,name=updateItems,proto3" json:"updateItems,omitempty"`
}

func (x *StrategyGroupDiffReply) Reset() {
	*x = StrategyGroupDiffReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_load_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategyGroupDiffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyGroupDiffReply) ProtoMessage() {}

func (x *StrategyGroupDiffReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_load_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyGroupDiffReply.ProtoReflect.Descriptor instead.
func (*StrategyGroupDiffReply) Descriptor() ([]byte, []int) {
	return file_agent_load_proto_rawDescGZIP(), []int{3}
}

func (x *StrategyGroupDiffReply) GetAppendItems() []*api.GroupSimple {
	if x != nil {
		return x.AppendItems
	}
	return nil
}

func (x *StrategyGroupDiffReply) GetDeleteItems() []*api.GroupSimple {
	if x != nil {
		return x.DeleteItems
	}
	return nil
}

func (x *StrategyGroupDiffReply) GetUpdateItems() []*api.GroupSimple {
	if x != nil {
		return x.UpdateItems
	}
	return nil
}

type EvaluateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupList []*api.GroupSimple `protobuf:"bytes,1,rep,name=groupList,proto3" json:"groupList,omitempty"`
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_load_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_load_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_agent_load_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluateRequest) GetGroupList() []*api.GroupSimple {
	if x != nil {
		return x.GroupList
	}
	return nil
}

type EvaluateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EvaluateReply) Reset() {
	*x = EvaluateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_load_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateReply) ProtoMessage() {}

func (x *EvaluateReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_load_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateReply.ProtoReflect.Descriptor instead.
func (*EvaluateReply) Descriptor() ([]byte, []int) {
	return file_agent_load_proto_rawDescGZIP(), []int{5}
}

var File_agent_load_proto protoreflect.FileDescriptor

var file_agent_load_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x0b, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67,
	0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e,
	0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x1a,
	0x0a, 0x18, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44,
	0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xb4, 0x01, 0x0a, 0x16, 0x53,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x69, 0x66, 0x66,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x0b, 0x61, 0x70,
	0x70, 0x65, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x32, 0x0a, 0x0b, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x32, 0x0a,
	0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x52, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x41, 0x0a, 0x0f, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x48, 0x0a, 0x04, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x40, 0x0a,
	0x08, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x31, 0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x01, 0x5a, 0x22,
	0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x3b, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_load_proto_rawDescOnce sync.Once
	file_agent_load_proto_rawDescData = file_agent_load_proto_rawDesc
)

func file_agent_load_proto_rawDescGZIP() []byte {
	file_agent_load_proto_rawDescOnce.Do(func() {
		file_agent_load_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_load_proto_rawDescData)
	})
	return file_agent_load_proto_rawDescData
}

var file_agent_load_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agent_load_proto_goTypes = []interface{}{
	(*StrategyGroupAllRequest)(nil),  // 0: api.agent.StrategyGroupAllRequest
	(*StrategyGroupAllReply)(nil),    // 1: api.agent.StrategyGroupAllReply
	(*StrategyGroupDiffRequest)(nil), // 2: api.agent.StrategyGroupDiffRequest
	(*StrategyGroupDiffReply)(nil),   // 3: api.agent.StrategyGroupDiffReply
	(*EvaluateRequest)(nil),          // 4: api.agent.EvaluateRequest
	(*EvaluateReply)(nil),            // 5: api.agent.EvaluateReply
	(*api.GroupSimple)(nil),          // 6: api.GroupSimple
}
var file_agent_load_proto_depIdxs = []int32{
	6, // 0: api.agent.StrategyGroupAllReply.groupList:type_name -> api.GroupSimple
	6, // 1: api.agent.StrategyGroupDiffReply.appendItems:type_name -> api.GroupSimple
	6, // 2: api.agent.StrategyGroupDiffReply.deleteItems:type_name -> api.GroupSimple
	6, // 3: api.agent.StrategyGroupDiffReply.updateItems:type_name -> api.GroupSimple
	6, // 4: api.agent.EvaluateRequest.groupList:type_name -> api.GroupSimple
	4, // 5: api.agent.Load.Evaluate:input_type -> api.agent.EvaluateRequest
	5, // 6: api.agent.Load.Evaluate:output_type -> api.agent.EvaluateReply
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_agent_load_proto_init() }
func file_agent_load_proto_init() {
	if File_agent_load_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_load_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategyGroupAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_load_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategyGroupAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_load_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategyGroupDiffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_load_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategyGroupDiffReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_load_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_load_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_load_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_load_proto_goTypes,
		DependencyIndexes: file_agent_load_proto_depIdxs,
		MessageInfos:      file_agent_load_proto_msgTypes,
	}.Build()
	File_agent_load_proto = out.File
	file_agent_load_proto_rawDesc = nil
	file_agent_load_proto_goTypes = nil
	file_agent_load_proto_depIdxs = nil
}
