apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moon

resources:
  - namespace.yaml
  - secrets.yaml
  - goddess
  - rabbit
  - marksman
  - jade-tree
  - ingress

# Update image tags for all services at once.
images:
  - name: ghcr.io/aide-family/moon/goddess
    newTag: v0.0.2
  - name: ghcr.io/aide-family/moon/rabbit
    newTag: v0.0.2
  - name: ghcr.io/aide-family/moon/marksman
    newTag: v0.0.2
  - name: ghcr.io/aide-family/moon/jade_tree
    newTag: v0.0.2
