apiVersion: v1
kind: ConfigMap
metadata:
  name: marksman-config
  namespace: moon
  labels:
    app.kubernetes.io/name: marksman
    app.kubernetes.io/part-of: moon
data:
  server.yaml: |
    environment: PROD
    enableSwagger: false
    enableMetrics: true
    useRandomID: false

    server:
      name: marksman
      metadata:
        tag: marksman
        repository: https://github.com/aide-family/moon
        author: Aide Family
        email: aidecloud@163.com
      http:
        address: "0.0.0.0:8003"
        network: tcp
        timeout: 10s
        protocol: HTTP
      grpc:
        address: "0.0.0.0:9003"
        network: tcp
        timeout: 10s
        protocol: GRPC

    jwt:
      secret: placeholder
      expire: 60000s
      issuer: marksman

    serviceKey:
      allowedKeys:
        - sk-rabbit-dev

    goddessDomain:
      endpoints: http://goddess.moon.svc.cluster.local:8000
      network: HTTP
      timeout: 10s
      serviceKey: sk-marksman-dev

    rabbitDomain:
      endpoints: http://rabbit.moon.svc.cluster.local:8001
      network: HTTP
      timeout: 10s
      serviceKey: sk-marksman-dev

    evaluateConfig:
      concurrencyLimit: 10
      startupDelay: 10s
      queryTimeout: 10s
      appendChannelCapacity: 100
      removeChannelCapacity: 100

    mainTsdb:
      driver: METRICS_PROMETHEUS
      url: http://prometheus.monitoring.svc.cluster.local:9090
      basicAuth:
        enabled: false

    swaggerBasicAuth:
      enabled: false

    metricsBasicAuth:
      enabled: false

    oauth2:
      enable: false

    database:
      dialector: SQLITE
      debug: false
      useSystemLogger: false
      options:
        "@type": type.googleapis.com/magicbox.config.SQLiteOptions
        dsn: file:/data/marksman.db?cache=shared
