apiVersion: v1
kind: Service
metadata:
  name: marksman
  namespace: moon
  labels:
    app.kubernetes.io/name: marksman
    app.kubernetes.io/part-of: moon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: marksman
  ports:
    - name: http
      port: 8003
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9003
      targetPort: grpc
      protocol: TCP
