apiVersion: v1
kind: Service
metadata:
  name: rabbit
  namespace: moon
  labels:
    app.kubernetes.io/name: rabbit
    app.kubernetes.io/part-of: moon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbit
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9001
      targetPort: grpc
      protocol: TCP
    - name: job
      port: 7001
      targetPort: job
      protocol: TCP
