// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/aide-family/rabbit/internal/data/impl/do"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newWebhookConfig(db *gorm.DB, opts ...gen.DOOption) webhookConfig {
	_webhookConfig := webhookConfig{}

	_webhookConfig.webhookConfigDo.UseDB(db, opts...)
	_webhookConfig.webhookConfigDo.UseModel(&do.WebhookConfig{})

	tableName := _webhookConfig.webhookConfigDo.TableName()
	_webhookConfig.ALL = field.NewAsterisk(tableName)
	_webhookConfig.ID = field.NewInt64(tableName, "id")
	_webhookConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_webhookConfig.UpdatedAt = field.NewTime(tableName, "updated_at")
	_webhookConfig.Creator = field.NewInt64(tableName, "creator")
	_webhookConfig.DeletedAt = field.NewField(tableName, "deleted_at")
	_webhookConfig.NamespaceUID = field.NewInt64(tableName, "namespace_uid")
	_webhookConfig.Name = field.NewString(tableName, "name")
	_webhookConfig.App = field.NewInt32(tableName, "app")
	_webhookConfig.URL = field.NewString(tableName, "url")
	_webhookConfig.Method = field.NewInt32(tableName, "method")
	_webhookConfig.Headers = field.NewField(tableName, "headers")
	_webhookConfig.Secret = field.NewField(tableName, "secret")
	_webhookConfig.Status = field.NewInt32(tableName, "status")

	_webhookConfig.fillFieldMap()

	return _webhookConfig
}

type webhookConfig struct {
	webhookConfigDo

	ALL          field.Asterisk
	ID           field.Int64
	CreatedAt    field.Time
	UpdatedAt    field.Time
	Creator      field.Int64
	DeletedAt    field.Field
	NamespaceUID field.Int64
	Name         field.String
	App          field.Int32
	URL          field.String
	Method       field.Int32
	Headers      field.Field
	Secret       field.Field
	Status       field.Int32

	fieldMap map[string]field.Expr
}

func (w webhookConfig) Table(newTableName string) *webhookConfig {
	w.webhookConfigDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w webhookConfig) As(alias string) *webhookConfig {
	w.webhookConfigDo.DO = *(w.webhookConfigDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *webhookConfig) updateTableName(table string) *webhookConfig {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")
	w.Creator = field.NewInt64(table, "creator")
	w.DeletedAt = field.NewField(table, "deleted_at")
	w.NamespaceUID = field.NewInt64(table, "namespace_uid")
	w.Name = field.NewString(table, "name")
	w.App = field.NewInt32(table, "app")
	w.URL = field.NewString(table, "url")
	w.Method = field.NewInt32(table, "method")
	w.Headers = field.NewField(table, "headers")
	w.Secret = field.NewField(table, "secret")
	w.Status = field.NewInt32(table, "status")

	w.fillFieldMap()

	return w
}

func (w *webhookConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *webhookConfig) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 13)
	w.fieldMap["id"] = w.ID
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["creator"] = w.Creator
	w.fieldMap["deleted_at"] = w.DeletedAt
	w.fieldMap["namespace_uid"] = w.NamespaceUID
	w.fieldMap["name"] = w.Name
	w.fieldMap["app"] = w.App
	w.fieldMap["url"] = w.URL
	w.fieldMap["method"] = w.Method
	w.fieldMap["headers"] = w.Headers
	w.fieldMap["secret"] = w.Secret
	w.fieldMap["status"] = w.Status
}

func (w webhookConfig) clone(db *gorm.DB) webhookConfig {
	w.webhookConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w webhookConfig) replaceDB(db *gorm.DB) webhookConfig {
	w.webhookConfigDo.ReplaceDB(db)
	return w
}

type webhookConfigDo struct{ gen.DO }

type IWebhookConfigDo interface {
	gen.SubQuery
	Debug() IWebhookConfigDo
	WithContext(ctx context.Context) IWebhookConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWebhookConfigDo
	WriteDB() IWebhookConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWebhookConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWebhookConfigDo
	Not(conds ...gen.Condition) IWebhookConfigDo
	Or(conds ...gen.Condition) IWebhookConfigDo
	Select(conds ...field.Expr) IWebhookConfigDo
	Where(conds ...gen.Condition) IWebhookConfigDo
	Order(conds ...field.Expr) IWebhookConfigDo
	Distinct(cols ...field.Expr) IWebhookConfigDo
	Omit(cols ...field.Expr) IWebhookConfigDo
	Join(table schema.Tabler, on ...field.Expr) IWebhookConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWebhookConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWebhookConfigDo
	Group(cols ...field.Expr) IWebhookConfigDo
	Having(conds ...gen.Condition) IWebhookConfigDo
	Limit(limit int) IWebhookConfigDo
	Offset(offset int) IWebhookConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWebhookConfigDo
	Unscoped() IWebhookConfigDo
	Create(values ...*do.WebhookConfig) error
	CreateInBatches(values []*do.WebhookConfig, batchSize int) error
	Save(values ...*do.WebhookConfig) error
	First() (*do.WebhookConfig, error)
	Take() (*do.WebhookConfig, error)
	Last() (*do.WebhookConfig, error)
	Find() ([]*do.WebhookConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*do.WebhookConfig, err error)
	FindInBatches(result *[]*do.WebhookConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*do.WebhookConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWebhookConfigDo
	Assign(attrs ...field.AssignExpr) IWebhookConfigDo
	Joins(fields ...field.RelationField) IWebhookConfigDo
	Preload(fields ...field.RelationField) IWebhookConfigDo
	FirstOrInit() (*do.WebhookConfig, error)
	FirstOrCreate() (*do.WebhookConfig, error)
	FindByPage(offset int, limit int) (result []*do.WebhookConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWebhookConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w webhookConfigDo) Debug() IWebhookConfigDo {
	return w.withDO(w.DO.Debug())
}

func (w webhookConfigDo) WithContext(ctx context.Context) IWebhookConfigDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w webhookConfigDo) ReadDB() IWebhookConfigDo {
	return w.Clauses(dbresolver.Read)
}

func (w webhookConfigDo) WriteDB() IWebhookConfigDo {
	return w.Clauses(dbresolver.Write)
}

func (w webhookConfigDo) Session(config *gorm.Session) IWebhookConfigDo {
	return w.withDO(w.DO.Session(config))
}

func (w webhookConfigDo) Clauses(conds ...clause.Expression) IWebhookConfigDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w webhookConfigDo) Returning(value interface{}, columns ...string) IWebhookConfigDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w webhookConfigDo) Not(conds ...gen.Condition) IWebhookConfigDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w webhookConfigDo) Or(conds ...gen.Condition) IWebhookConfigDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w webhookConfigDo) Select(conds ...field.Expr) IWebhookConfigDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w webhookConfigDo) Where(conds ...gen.Condition) IWebhookConfigDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w webhookConfigDo) Order(conds ...field.Expr) IWebhookConfigDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w webhookConfigDo) Distinct(cols ...field.Expr) IWebhookConfigDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w webhookConfigDo) Omit(cols ...field.Expr) IWebhookConfigDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w webhookConfigDo) Join(table schema.Tabler, on ...field.Expr) IWebhookConfigDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w webhookConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWebhookConfigDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w webhookConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IWebhookConfigDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w webhookConfigDo) Group(cols ...field.Expr) IWebhookConfigDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w webhookConfigDo) Having(conds ...gen.Condition) IWebhookConfigDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w webhookConfigDo) Limit(limit int) IWebhookConfigDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w webhookConfigDo) Offset(offset int) IWebhookConfigDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w webhookConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWebhookConfigDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w webhookConfigDo) Unscoped() IWebhookConfigDo {
	return w.withDO(w.DO.Unscoped())
}

func (w webhookConfigDo) Create(values ...*do.WebhookConfig) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w webhookConfigDo) CreateInBatches(values []*do.WebhookConfig, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w webhookConfigDo) Save(values ...*do.WebhookConfig) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w webhookConfigDo) First() (*do.WebhookConfig, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*do.WebhookConfig), nil
	}
}

func (w webhookConfigDo) Take() (*do.WebhookConfig, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*do.WebhookConfig), nil
	}
}

func (w webhookConfigDo) Last() (*do.WebhookConfig, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*do.WebhookConfig), nil
	}
}

func (w webhookConfigDo) Find() ([]*do.WebhookConfig, error) {
	result, err := w.DO.Find()
	return result.([]*do.WebhookConfig), err
}

func (w webhookConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*do.WebhookConfig, err error) {
	buf := make([]*do.WebhookConfig, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w webhookConfigDo) FindInBatches(result *[]*do.WebhookConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w webhookConfigDo) Attrs(attrs ...field.AssignExpr) IWebhookConfigDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w webhookConfigDo) Assign(attrs ...field.AssignExpr) IWebhookConfigDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w webhookConfigDo) Joins(fields ...field.RelationField) IWebhookConfigDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w webhookConfigDo) Preload(fields ...field.RelationField) IWebhookConfigDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w webhookConfigDo) FirstOrInit() (*do.WebhookConfig, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*do.WebhookConfig), nil
	}
}

func (w webhookConfigDo) FirstOrCreate() (*do.WebhookConfig, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*do.WebhookConfig), nil
	}
}

func (w webhookConfigDo) FindByPage(offset int, limit int) (result []*do.WebhookConfig, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w webhookConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w webhookConfigDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w webhookConfigDo) Delete(models ...*do.WebhookConfig) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *webhookConfigDo) withDO(do gen.Dao) *webhookConfigDo {
	w.DO = *do.(*gen.DO)
	return w
}
