data:
  cache:
    driver: ${X_MOON_RABBIT_DATA_CACHE_DRIVER:MEMORY}
    network: ${X_MOON_RABBIT_DATA_CACHE_NETWORK:tcp}
    addr: ${X_MOON_RABBIT_DATA_CACHE_ADDR:127.0.0.1:6379}
    password: ${X_MOON_RABBIT_DATA_CACHE_PASSWORD}
    db: ${X_MOON_RABBIT_DATA_CACHE_DB:0}
    readTimeout: ${X_MOON_RABBIT_DATA_CACHE_READ_TIMEOUT:5s}
    writeTimeout: ${X_MOON_RABBIT_DATA_CACHE_WRITE_TIMEOUT:5s}
    dialTimeout: ${X_MOON_RABBIT_DATA_CACHE_DIAL_TIMEOUT:5s}
