// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: marksman/api/v1/strategy_metric.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StrategyMetric_SaveStrategyMetric_FullMethodName              = "/marksman.api.v1.StrategyMetric/SaveStrategyMetric"
	StrategyMetric_GetStrategyMetric_FullMethodName               = "/marksman.api.v1.StrategyMetric/GetStrategyMetric"
	StrategyMetric_SaveStrategyMetricLevel_FullMethodName         = "/marksman.api.v1.StrategyMetric/SaveStrategyMetricLevel"
	StrategyMetric_UpdateStrategyMetricLevelStatus_FullMethodName = "/marksman.api.v1.StrategyMetric/UpdateStrategyMetricLevelStatus"
	StrategyMetric_DeleteStrategyMetricLevel_FullMethodName       = "/marksman.api.v1.StrategyMetric/DeleteStrategyMetricLevel"
	StrategyMetric_GetStrategyMetricLevel_FullMethodName          = "/marksman.api.v1.StrategyMetric/GetStrategyMetricLevel"
	StrategyMetric_StrategyMetricBindReceivers_FullMethodName     = "/marksman.api.v1.StrategyMetric/StrategyMetricBindReceivers"
)

// StrategyMetricClient is the client API for StrategyMetric service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategyMetricClient interface {
	SaveStrategyMetric(ctx context.Context, in *SaveStrategyMetricRequest, opts ...grpc.CallOption) (*SaveStrategyMetricReply, error)
	GetStrategyMetric(ctx context.Context, in *GetStrategyMetricRequest, opts ...grpc.CallOption) (*StrategyMetricItem, error)
	SaveStrategyMetricLevel(ctx context.Context, in *SaveStrategyMetricLevelRequest, opts ...grpc.CallOption) (*SaveStrategyMetricLevelReply, error)
	UpdateStrategyMetricLevelStatus(ctx context.Context, in *UpdateStrategyMetricLevelStatusRequest, opts ...grpc.CallOption) (*UpdateStrategyMetricLevelStatusReply, error)
	DeleteStrategyMetricLevel(ctx context.Context, in *DeleteStrategyMetricLevelRequest, opts ...grpc.CallOption) (*DeleteStrategyMetricLevelReply, error)
	GetStrategyMetricLevel(ctx context.Context, in *GetStrategyMetricLevelRequest, opts ...grpc.CallOption) (*StrategyMetricLevelItem, error)
	StrategyMetricBindReceivers(ctx context.Context, in *StrategyMetricBindReceiversRequest, opts ...grpc.CallOption) (*StrategyMetricBindReceiversReply, error)
}

type strategyMetricClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyMetricClient(cc grpc.ClientConnInterface) StrategyMetricClient {
	return &strategyMetricClient{cc}
}

func (c *strategyMetricClient) SaveStrategyMetric(ctx context.Context, in *SaveStrategyMetricRequest, opts ...grpc.CallOption) (*SaveStrategyMetricReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveStrategyMetricReply)
	err := c.cc.Invoke(ctx, StrategyMetric_SaveStrategyMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyMetricClient) GetStrategyMetric(ctx context.Context, in *GetStrategyMetricRequest, opts ...grpc.CallOption) (*StrategyMetricItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyMetricItem)
	err := c.cc.Invoke(ctx, StrategyMetric_GetStrategyMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyMetricClient) SaveStrategyMetricLevel(ctx context.Context, in *SaveStrategyMetricLevelRequest, opts ...grpc.CallOption) (*SaveStrategyMetricLevelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveStrategyMetricLevelReply)
	err := c.cc.Invoke(ctx, StrategyMetric_SaveStrategyMetricLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyMetricClient) UpdateStrategyMetricLevelStatus(ctx context.Context, in *UpdateStrategyMetricLevelStatusRequest, opts ...grpc.CallOption) (*UpdateStrategyMetricLevelStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyMetricLevelStatusReply)
	err := c.cc.Invoke(ctx, StrategyMetric_UpdateStrategyMetricLevelStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyMetricClient) DeleteStrategyMetricLevel(ctx context.Context, in *DeleteStrategyMetricLevelRequest, opts ...grpc.CallOption) (*DeleteStrategyMetricLevelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStrategyMetricLevelReply)
	err := c.cc.Invoke(ctx, StrategyMetric_DeleteStrategyMetricLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyMetricClient) GetStrategyMetricLevel(ctx context.Context, in *GetStrategyMetricLevelRequest, opts ...grpc.CallOption) (*StrategyMetricLevelItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyMetricLevelItem)
	err := c.cc.Invoke(ctx, StrategyMetric_GetStrategyMetricLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyMetricClient) StrategyMetricBindReceivers(ctx context.Context, in *StrategyMetricBindReceiversRequest, opts ...grpc.CallOption) (*StrategyMetricBindReceiversReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyMetricBindReceiversReply)
	err := c.cc.Invoke(ctx, StrategyMetric_StrategyMetricBindReceivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyMetricServer is the server API for StrategyMetric service.
// All implementations must embed UnimplementedStrategyMetricServer
// for forward compatibility.
type StrategyMetricServer interface {
	SaveStrategyMetric(context.Context, *SaveStrategyMetricRequest) (*SaveStrategyMetricReply, error)
	GetStrategyMetric(context.Context, *GetStrategyMetricRequest) (*StrategyMetricItem, error)
	SaveStrategyMetricLevel(context.Context, *SaveStrategyMetricLevelRequest) (*SaveStrategyMetricLevelReply, error)
	UpdateStrategyMetricLevelStatus(context.Context, *UpdateStrategyMetricLevelStatusRequest) (*UpdateStrategyMetricLevelStatusReply, error)
	DeleteStrategyMetricLevel(context.Context, *DeleteStrategyMetricLevelRequest) (*DeleteStrategyMetricLevelReply, error)
	GetStrategyMetricLevel(context.Context, *GetStrategyMetricLevelRequest) (*StrategyMetricLevelItem, error)
	StrategyMetricBindReceivers(context.Context, *StrategyMetricBindReceiversRequest) (*StrategyMetricBindReceiversReply, error)
	mustEmbedUnimplementedStrategyMetricServer()
}

// UnimplementedStrategyMetricServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategyMetricServer struct{}

func (UnimplementedStrategyMetricServer) SaveStrategyMetric(context.Context, *SaveStrategyMetricRequest) (*SaveStrategyMetricReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveStrategyMetric not implemented")
}
func (UnimplementedStrategyMetricServer) GetStrategyMetric(context.Context, *GetStrategyMetricRequest) (*StrategyMetricItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrategyMetric not implemented")
}
func (UnimplementedStrategyMetricServer) SaveStrategyMetricLevel(context.Context, *SaveStrategyMetricLevelRequest) (*SaveStrategyMetricLevelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveStrategyMetricLevel not implemented")
}
func (UnimplementedStrategyMetricServer) UpdateStrategyMetricLevelStatus(context.Context, *UpdateStrategyMetricLevelStatusRequest) (*UpdateStrategyMetricLevelStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyMetricLevelStatus not implemented")
}
func (UnimplementedStrategyMetricServer) DeleteStrategyMetricLevel(context.Context, *DeleteStrategyMetricLevelRequest) (*DeleteStrategyMetricLevelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStrategyMetricLevel not implemented")
}
func (UnimplementedStrategyMetricServer) GetStrategyMetricLevel(context.Context, *GetStrategyMetricLevelRequest) (*StrategyMetricLevelItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrategyMetricLevel not implemented")
}
func (UnimplementedStrategyMetricServer) StrategyMetricBindReceivers(context.Context, *StrategyMetricBindReceiversRequest) (*StrategyMetricBindReceiversReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StrategyMetricBindReceivers not implemented")
}
func (UnimplementedStrategyMetricServer) mustEmbedUnimplementedStrategyMetricServer() {}
func (UnimplementedStrategyMetricServer) testEmbeddedByValue()                        {}

// UnsafeStrategyMetricServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyMetricServer will
// result in compilation errors.
type UnsafeStrategyMetricServer interface {
	mustEmbedUnimplementedStrategyMetricServer()
}

func RegisterStrategyMetricServer(s grpc.ServiceRegistrar, srv StrategyMetricServer) {
	// If the following call pancis, it indicates UnimplementedStrategyMetricServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StrategyMetric_ServiceDesc, srv)
}

func _StrategyMetric_SaveStrategyMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveStrategyMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyMetricServer).SaveStrategyMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyMetric_SaveStrategyMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyMetricServer).SaveStrategyMetric(ctx, req.(*SaveStrategyMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyMetric_GetStrategyMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategyMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyMetricServer).GetStrategyMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyMetric_GetStrategyMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyMetricServer).GetStrategyMetric(ctx, req.(*GetStrategyMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyMetric_SaveStrategyMetricLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveStrategyMetricLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyMetricServer).SaveStrategyMetricLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyMetric_SaveStrategyMetricLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyMetricServer).SaveStrategyMetricLevel(ctx, req.(*SaveStrategyMetricLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyMetric_UpdateStrategyMetricLevelStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyMetricLevelStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyMetricServer).UpdateStrategyMetricLevelStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyMetric_UpdateStrategyMetricLevelStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyMetricServer).UpdateStrategyMetricLevelStatus(ctx, req.(*UpdateStrategyMetricLevelStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyMetric_DeleteStrategyMetricLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStrategyMetricLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyMetricServer).DeleteStrategyMetricLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyMetric_DeleteStrategyMetricLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyMetricServer).DeleteStrategyMetricLevel(ctx, req.(*DeleteStrategyMetricLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyMetric_GetStrategyMetricLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategyMetricLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyMetricServer).GetStrategyMetricLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyMetric_GetStrategyMetricLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyMetricServer).GetStrategyMetricLevel(ctx, req.(*GetStrategyMetricLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyMetric_StrategyMetricBindReceivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyMetricBindReceiversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyMetricServer).StrategyMetricBindReceivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyMetric_StrategyMetricBindReceivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyMetricServer).StrategyMetricBindReceivers(ctx, req.(*StrategyMetricBindReceiversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StrategyMetric_ServiceDesc is the grpc.ServiceDesc for StrategyMetric service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StrategyMetric_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marksman.api.v1.StrategyMetric",
	HandlerType: (*StrategyMetricServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveStrategyMetric",
			Handler:    _StrategyMetric_SaveStrategyMetric_Handler,
		},
		{
			MethodName: "GetStrategyMetric",
			Handler:    _StrategyMetric_GetStrategyMetric_Handler,
		},
		{
			MethodName: "SaveStrategyMetricLevel",
			Handler:    _StrategyMetric_SaveStrategyMetricLevel_Handler,
		},
		{
			MethodName: "UpdateStrategyMetricLevelStatus",
			Handler:    _StrategyMetric_UpdateStrategyMetricLevelStatus_Handler,
		},
		{
			MethodName: "DeleteStrategyMetricLevel",
			Handler:    _StrategyMetric_DeleteStrategyMetricLevel_Handler,
		},
		{
			MethodName: "GetStrategyMetricLevel",
			Handler:    _StrategyMetric_GetStrategyMetricLevel_Handler,
		},
		{
			MethodName: "StrategyMetricBindReceivers",
			Handler:    _StrategyMetric_StrategyMetricBindReceivers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marksman/api/v1/strategy_metric.proto",
}
