eventBus:
  strategyJobEventBusMaxCap: ${X_MOON_HOUYI_STRATEGY_JOB_EVENT_BUS_MAX_CAP:10000}
  alertEventBusMaxCap: ${X_MOON_HOUYI_ALERT_EVENT_BUS_MAX_CAP:10000}
  alertEventJobBusMaxCap: ${X_MOON_HOUYI_ALERT_EVENT_JOB_BUS_MAX_CAP:10000}