apiVersion: v1
kind: Namespace
metadata:
  name: moon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: moon-agent
  namespace: moon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: moon-server
  namespace: moon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: moon-agent-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: moon-server-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moon-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: moon-agent-role
subjects:
- kind: ServiceAccount
  name: moon-agent
  namespace: moon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moon-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: moon-server-role
subjects:
- kind: ServiceAccount
  name: moon-server
  namespace: moon
---
apiVersion: v1
data:
  config.yaml: |-
    env:
      name: moon_agent
      version: 0.0.1
      env: dev
      metadata:
        description: Prometheus Manager Agent APP
        version: 0.0.1
        author: 梧桐
        license: MIT
        email: aidecloud@163.com
        url: https://github.com/aide-family/moon
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 1s
      grpc:
        addr: 0.0.0.0:9000
        timeout: 1s
    log:
      filename: ./log/agent.log
      level: debug
      encoder: json
      maxSize: 500
      compress: true
    # NOTE: 实际运行中需要替换为容器可访问地址，当前主机为容器在本地一站式拉起可访问的主机地址，生产根据自身配置修改
    interflow:
      version: v2
      watchProm:
        interval: 10s
      hook:
        http:
          agent:
            url: http://moon-agent-svc.moon.svc.cluster.local:8000/api/v1/interflows/receive
          server:
            url: http://moon-server-svc.moon.svc.cluster.local:8000/api/v1/interflows/receive
kind: ConfigMap
metadata:
  name: moon-agent-config
  namespace: moon
---
apiVersion: v1
data:
  config.yaml: |-
    env:
      name: moon_server
      version: 0.0.1
      env: dev
      metadata:
        description: Prometheus Manager Server APP
        version: 0.0.1
        author: 梧桐
        license: MIT
        email: aidecloud@163.com
        url: https://github.com/aide-family/moon
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 1s
      grpc:
        addr: 0.0.0.0:9000
        timeout: 1s
      ws:
        addr: 0.0.0.0:8888
        timeout: 1s
    data:
      database:
        driver: sqlite
        source: ./db/init_sqlite.db
        debug: true
    log:
      filename: ./log/server.log
      level: debug
      encoder: json
      maxSize: 500
      compress: true
    apiWhite:
      all:
        - /api.server.auth.Auth/Login
        - /api.server.auth.Auth/Captcha
        - /api.interflows.HookInterflow/Receive
        - /api.ping.Ping/Check
      jwtApi:
      rbacApi:
        - /api.server.auth.Auth/Logout
        - /api.server.auth.Auth/RefreshToken
    interflow:
      version: v2
      hook:
        network: http
kind: ConfigMap
metadata:
  name: moon-server-config
  namespace: moon
---
apiVersion: v1
kind: Service
metadata:
  labels:
    apps.moon/name: moon-agent-svc
  name: moon-agent-svc
  namespace: moon
spec:
  ports:
  - name: http
    nodePort: 31081
    port: 8000
    targetPort: 8000
  - name: grpc
    nodePort: 31091
    port: 9000
    targetPort: 9000
  selector:
    apps.moon/name: moon-agent
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    apps.moon/name: moon-server-svc
  name: moon-server-svc
  namespace: moon
spec:
  ports:
  - name: http
    nodePort: 31080
    port: 8000
    targetPort: 8000
  - name: grpc
    nodePort: 31090
    port: 9000
    targetPort: 9000
  - name: ws
    port: 8888
    targetPort: 8888
  - name: nginx
    nodePort: 31008
    port: 80
    targetPort: 80
  selector:
    apps.moon/name: moon-server
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: moon-sqlite-pv-5gi
  namespace: moon
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /nfs/data/moon/sqlite
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moon-sqlite-pvc
  namespace: moon
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps.moon/name: moon-agent
  name: moon-agent
  namespace: moon
spec:
  replicas: 1
  selector:
    matchLabels:
      apps.moon/name: moon-agent
  template:
    metadata:
      labels:
        apps.moon/name: moon-agent
    spec:
      containers:
      - args:
        - --conf=/config/config.yaml
        command:
        - ./prom_agent
        image: aidemoonio/moon-agent:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /ping
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        name: moon-agent
        readinessProbe:
          httpGet:
            path: /ping
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /config
          name: moon-agent-config
      serviceAccountName: moon-agent
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: moon-agent-config
        name: moon-agent-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps.moon/name: moon-server
  name: moon-server
  namespace: moon
spec:
  replicas: 1
  selector:
    matchLabels:
      apps.moon/name: moon-server
  template:
    metadata:
      labels:
        apps.moon/name: moon-server
    spec:
      containers:
      - command:
        - bash
        - -c
        - nginx && ./prom_server --conf=/config/config.yaml
        image: aidemoonio/moon-server:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /ping
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        name: moon-server
        readinessProbe:
          httpGet:
            path: /ping
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /config
          name: moon-server-config
        - mountPath: /app/db
          name: moon-server-sqlite-volume
      serviceAccountName: moon-server
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: moon-server-config
        name: moon-server-config
      - name: moon-server-sqlite-volume
        persistentVolumeClaim:
          claimName: moon-sqlite-pvc
