apiVersion: v1
kind: Service
metadata:
  name: goddess
  namespace: moon
  labels:
    app.kubernetes.io/name: goddess
    app.kubernetes.io/part-of: moon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: goddess
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9000
      targetPort: grpc
      protocol: TCP
