auth:
  jwt:
    signKey: ${X_MOON_LAUREL_AUTH_JWT_SIGN_KEY:laurel-sign-key}
    issuer: ${X_MOON_LAUREL_AUTH_JWT_ISSUER:moon.laurel}
    expire: ${X_MOON_LAUREL_AUTH_JWT_EXPIRE:3600s}
    allowOperations:
      - /api.common.Health/Check
