environment: DEV
useRandomID: 'true'
enableSwagger: 'true'
enableMetrics: 'true'
enableClientConfig: 'false'

server:
  name: jade_tree
  metadata:
    owner: aide-family
    role: agent-collector
  http:
    network: tcp
    address: 0.0.0.0:8004
    timeout: 1s
    protocol: PROTOCOL_HTTP
  grpc:
    network: tcp
    address: 0.0.0.0:9004
    timeout: 1s
    protocol: PROTOCOL_GRPC

swaggerBasicAuth:
  username: admin
  password: admin

metricsBasicAuth:
  username: admin
  password: admin

jwt:
  secret: change-me

database:
  dialector: SQLITE
  debug: 'true'
  useSystemLogger: 'false'
  options:
    '@type': type.googleapis.com/magicbox.config.SQLiteOptions
    dsn: 'file:./jade_tree.db?cache=shared'
