environment: ${MOON_JADE_TREE_ENVIRONMENT:PROD}
enableSwagger: ${MOON_JADE_TREE_ENABLE_SWAGGER:true}
enableMetrics: ${MOON_JADE_TREE_ENABLE_METRICS:true}
useRandomID: ${MOON_JADE_TREE_USE_RANDOM_NODE_ID:false}
enableClientConfig: ${MOON_JADE_TREE_ENABLE_CLIENT_CONFIG:false}

server:
  name: ${MOON_JADE_TREE_SERVER_NAME:jade_tree}
  metadata:
    tag: ${MOON_JADE_TREE_METADATA_TAG:jade_tree}
    repository: ${MOON_JADE_TREE_METADATA_REPOSITORY:https://github.com/aide-family/jade_tree}
    author: ${MOON_JADE_TREE_METADATA_AUTHOR:Aide Family}
    email: ${MOON_JADE_TREE_METADATA_EMAIL:aidecloud@163.com}
  http:
    address: '${MOON_JADE_TREE_HTTP_ADDRESS:0.0.0.0:8004}'
    network: '${MOON_JADE_TREE_HTTP_NETWORK:tcp}'
    timeout: '${MOON_JADE_TREE_HTTP_TIMEOUT:10s}'
    protocol: HTTP
  grpc:
    address: '${MOON_JADE_TREE_GRPC_ADDRESS:0.0.0.0:9004}'
    network: '${MOON_JADE_TREE_GRPC_NETWORK:tcp}'
    timeout: '${MOON_JADE_TREE_GRPC_TIMEOUT:10s}'
    protocol: GRPC

swaggerBasicAuth:
  enabled: ${MOON_JADE_TREE_SWAGGER_BASIC_AUTH_ENABLED:false}
  username: ${MOON_JADE_TREE_SWAGGER_BASIC_AUTH_USERNAME:moon.jade_tree}
  password: ${MOON_JADE_TREE_SWAGGER_BASIC_AUTH_PASSWORD:jade_tree.swagger}

metricsBasicAuth:
  enabled: ${MOON_JADE_TREE_METRICS_BASIC_AUTH_ENABLED:false}
  username: ${MOON_JADE_TREE_METRICS_BASIC_AUTH_USERNAME:moon.jade_tree}
  password: ${MOON_JADE_TREE_METRICS_BASIC_AUTH_PASSWORD:jade_tree.metrics}

jwt:
  secret: '${MOON_JADE_TREE_JWT_SECRET:xxx}'
  expire: '${MOON_JADE_TREE_JWT_EXPIRE:60000s}'
  issuer: '${MOON_JADE_TREE_JWT_ISSUER:jade_tree}'

database:
  dialector: ${MOON_JADE_TREE_DATABASE_DIALECTOR:SQLITE}
  debug: ${MOON_JADE_TREE_DATABASE_DEBUG:true}
  useSystemLogger: ${MOON_JADE_TREE_DATABASE_USE_SYSTEM_LOGGER:false}
  options:
    '@type': '${MOON_JADE_TREE_DATABASE_OPTIONS_TYPE:type.googleapis.com/magicbox.config.SQLiteOptions}'
    dsn: '${MOON_JADE_TREE_DATABASE_SQLITE_OPTIONS_DSN:file:./jade_tree.db?cache=shared}'

probe:
  enabled: ${MOON_JADE_TREE_PROBE_ENABLED:false}
  timeout: '${MOON_JADE_TREE_PROBE_TIMEOUT:5s}'
  concurrency: ${MOON_JADE_TREE_PROBE_CONCURRENCY:32}
  initiator:
    hostname: ${MOON_JADE_TREE_PROBE_INITIATOR_HOSTNAME:}
    ip: ${MOON_JADE_TREE_PROBE_INITIATOR_IP:}
  targets:
    - type: tcp
      host: 127.0.0.1
      port: '8004'
      # name: jade_tree_tcp
      timeoutSeconds: 5
    - type: http
      url: http://127.0.0.1:8004/health
      # name: jade_tree_http
      timeoutSeconds: 5

collectSelf:
  enabled: ${MOON_JADE_TREE_COLLECT_SELF_ENABLED:true}
  timeout: '${MOON_JADE_TREE_COLLECT_SELF_TIMEOUT:60s}'
  interval: '${MOON_JADE_TREE_COLLECT_SELF_INTERVAL:60s}'
machineInfoReport:
  enabled: ${MOON_JADE_TREE_MACHINE_INFO_REPORT_ENABLED:false}
  interval: '${MOON_JADE_TREE_MACHINE_INFO_REPORT_INTERVAL:600s}'
  timeout: '${MOON_JADE_TREE_MACHINE_INFO_REPORT_TIMEOUT:10s}'
  endpoints:
    - ${MOON_JADE_TREE_MACHINE_INFO_REPORT_ENDPOINT_1:http://127.0.0.1:8004/v1/machine-info/report}
  headers:
    Authorization: ${MOON_JADE_TREE_MACHINE_INFO_REPORT_AUTHORIZATION:}
