apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jade-tree-data
  namespace: moon
  labels:
    app.kubernetes.io/name: jade-tree
    app.kubernetes.io/part-of: moon
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
