apiVersion: v1
kind: Service
metadata:
  name: jade-tree
  namespace: moon
  labels:
    app.kubernetes.io/name: jade-tree
    app.kubernetes.io/part-of: moon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jade-tree
  ports:
    - name: http
      port: 8004
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9004
      targetPort: grpc
      protocol: TCP
