# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [main, v3]
  pull_request:
    branches: [main, v3]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install protobuf
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install dependencies
        run: make init

      - name: Build Base
        run: make all app=palace && make all app=houyi && make all app=rabbit && make all app=laurel

      - name: Build Palace
        run: make build app=palace

      - name: Build Houyi
        run: make build app=houyi

      - name: Build Rabbit
        run: make build app=rabbit

      - name: Build Laurel
        run: make build app=laurel
