name: Docker Build and Push

on:
  push:
    tags:
      - 'v*' # 触发条件可以根据你的需求修改

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.REPO_PASS }}" | docker login -u "${{ secrets.REPO }}" --password-stdin

      - name: Build and push Docker image
        run: |
          make prom-server-docker-build REPO="${{ secrets.REPO }}"
          make prom-agent-docker-build REPO="${{ secrets.REPO }}"
          make prom-server-docker-push REPO="${{ secrets.REPO }}"
          make prom-agent-docker-push REPO="${{ secrets.REPO }}"
        env:
          REPO: ${{ secrets.REPO }}
          REPO_PASS: ${{ secrets.REPO_PASS }}
