package alarmmodel

const tableNameRealtimeAlarmPage = "realtime_alarm_page"

// RealtimeAlarmPage represents the realtime alarm pages model
type RealtimeAlarmPage struct {
	RealtimeAlarmID uint32 `gorm:"primaryKey;column:realtime_alarm_id;type:int;not null;comment:告警ID;" json:"realtime_alarm_id"`
	PageID          uint32 `gorm:"primaryKey;column:page_id;type:int;not null;comment:页面ID" json:"page_id"`
}

// TableName overrides the default table name generated by gorm
func (*RealtimeAlarmPage) TableName() string {
	return tableNameRealtimeAlarmPage
}
